### ISSUE TITLE
red sandstone incorrect model

### ISSUE THREAD

**Issue by peow** [Owehttamy/dds#1]
Red Sandstone Slab has a issue: 
![image](https://github.com/Owehttamy/dds/assets/105888751/98e40ee9-8bc9-43e4-9a57-0da6cf2d974d)

and a question: how can i edit the resourcepack to change the appearance of modded blocks? like "Checker Slab" from Supplementaries?
![image](https://github.com/Owehttamy/dds/assets/105888751/9e5b5050-3803-4205-bd52-79c40680fbbc)

**Comment by Owehttamy** [comment]
Super sorry for the incredibly long wait, @peow ! I didn't seem to get a notification for this issue.
The red sandstone problem has been solved, and I've now made it easier to add modded slab support. There is now a text file explaining the step-by-step process to add support to modded slabs in the resource pack folder. I hope this helps!

**Comment by peow** [comment]
thanks, youre the best
